# -*- coding: utf-8 -*-
"""prime_number1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySUSNeZVmEkiFes5qNAVaS8HAnwXYjqf
"""

num = int(input("Enter the number : "))
pri_ls=[]
for num in range(2,num):
    if all(num%i!=0 for i in range(2,num)):
      pri_ls.append(num)
print(pri_ls)